### ISSUE TITLE
ValueError: The passed save_path is not a valid checkpoint

### ISSUE THREAD

**Issue by 16619884724** [FrankCAN/GAPNet#1]
Hello,When I run   python.py    , everything is fine. When I continue to run    python evaluate.py --model=network --model_path=log/epoch_185_model.ckpt     an error occurred 
 "raceback (most recent call last):
  File "evaluate.py", line 169, in <module>
    evaluate(num_votes=12)
  File "evaluate.py", line 78, in evaluate
    saver.restore(sess, MODEL_PATH)
  File "/home/student908/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1538, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: log/epoch_185_model.ckpt",
I am using Xshell to connect to the server to run the program. I am not good at code, I want to know how to solve it, thank you

**Comment by 16619884724** [comment]
I think I found the cause of the problem. In my log folder, I didn't generate any epoch_xxx_model.ckpt files, because my best precision is only 0.916, and train.py sets avg_accuracy > 0.918 . when I set this  value samller, the model is started to generate in the log file, but why is it iteratively updated every time, and only 4-5 models can be left at the end? Why? Is the epoch_185_model.ckpt in the original code the best-precision epoch-generated model for testing your program? Looking forward to your answer

**Comment by FrankCAN** [comment]
Hi, you can set saver = tf.train.Saver(max_to_keep=250) in train.py, as the default setting is 5 models.

**Comment by 16619884724** [comment]
Thank you, I have saved a model that works well. After evaluation, the effect is fine. Would you like to have a plan for the pytorch code? Looking forward to your reply.


------------------ 原始邮件 ------------------
发件人: "FrankCAN"<notifications@github.com>;
发送时间: 2019年9月25日(星期三) 晚上9:11
收件人: "FrankCAN/GAPNet"<GAPNet@noreply.github.com>;
抄送: "Confession"<1773507074@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [FrankCAN/GAPNet] ValueError: The passed save_path is not a validcheckpoint (#1)




Hi, you can set saver = tf.train.Saver(max_to_keep=250) in train.py, as the default setting is 5 models.

**Comment by FrankCAN** [comment]
Hi, currently I have no plan for pytorch code, sorry for that, but I was suggested pytorch version might can achieve better performance.

**Comment by 16619884724** [comment]
Ok, anyway， thank you very much.






------------------ 原始邮件 ------------------
发件人: "FrankCAN"<notifications@github.com>;
发送时间: 2019年9月25日(星期三) 晚上9:59
收件人: "FrankCAN/GAPNet"<GAPNet@noreply.github.com>;
抄送: "Confession"<1773507074@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [FrankCAN/GAPNet] ValueError: The passed save_path is not a validcheckpoint (#1)




Hi, currently I have no plan for pytorch code, sorry for that, but I was suggested pytorch version might can achieve better performance.

**Comment by 16619884724** [comment]
Sorry to bother you again,in order to further integrate with my other frameworks ，I need to implement your paper with pytorch , but my programming ability is not enough. For me, this is a huge challenge. To be honest, I even don't know which file to start with.  Can you have any good suggestions?Thanks a million




------------------ 原始邮件 ------------------
发件人: "FrankCAN"<notifications@github.com>;
发送时间: 2019年9月25日(星期三) 晚上9:59
收件人: "FrankCAN/GAPNet"<GAPNet@noreply.github.com>;
抄送: "Confession"<1773507074@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [FrankCAN/GAPNet] ValueError: The passed save_path is not a validcheckpoint (#1)




Hi, currently I have no plan for pytorch code, sorry for that, but I was suggested pytorch version might can achieve better performance.

**Comment by FrankCAN** [comment]
Hi, can you please let me know what task you are going to do, classification or segmentation? As the code files are different for different tasks.

**Comment by 16619884724** [comment]
I would like to use the classification part of the framework, thank you！




------------------ 原始邮件 ------------------
发件人: "FrankCAN"<notifications@github.com>;
发送时间: 2019年9月28日(星期六) 凌晨0:14
收件人: "FrankCAN/GAPNet"<GAPNet@noreply.github.com>;
抄送: "Confession"<1773507074@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [FrankCAN/GAPNet] ValueError: The passed save_path is not a validcheckpoint (#1)




Hi, can you please let me know what task you are going to do, classification or segmentation? As the code files are different for different tasks.

**Comment by FrankCAN** [comment]
Hi, that's sample. You can start from train.py that organizes the dataset, and training process. Besides, the classification model is called by "pred, end_points = MODEL.get_model(pointclouds_pl, is_training_pl, bn_decay=bn_decay)". For the classification model, it is coded in network.py file in the models folder. And the model function is get_model(), and the loss function is get_loss(). Finally, all other scripts are supporting files, for example, gat_layers.py is graph attention model.

**Comment by 16619884724** [comment]
Ok, thank you very much for your kind help. I will start the code modification work according to your suggestion.




------------------ 原始邮件 ------------------
发件人: "FrankCAN"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 晚上8:48
收件人: "FrankCAN/GAPNet"<GAPNet@noreply.github.com>;
抄送: "Confession"<1773507074@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [FrankCAN/GAPNet] ValueError: The passed save_path is not a validcheckpoint (#1)




Hi, that's sample. You can start from train.py that organizes the dataset, and training process. Besides, the classification model is called by "pred, end_points = MODEL.get_model(pointclouds_pl, is_training_pl, bn_decay=bn_decay)". For the classification model, it is coded in network.py file in the models folder. And the model function is get_model(), and the loss function is get_loss(). Finally, all other scripts are supporting files, for example, gat_layers.py is graph attention model.

**Comment by 16619884724** [comment]
Sorry to bother you again. Recently I have to quote your article in some work, so I am writing the relevant pytorch code.
In the picture,  spatial transform network of the paper illustration shows NxKx6. I understand that the 6D dimension feature is fed into the spatial transform network, but the [output_dim] defined by [gat_layers.py] in the code is 16-dimensional (16 channels), which means that in your paper the spatial transform network called [input_transform_net]  has two inputs, one is 19-dimensional feature called [neighbors_features], and the other is 16-dimensional feature called [locals_max_transform]. What does this have to do with the NxKx6 displayed in the transformation matrix in the image? Did I understand wrong?, I am eager to get your answer, thank you very much.




------------------ 原始邮件 ------------------
发件人: "FrankCAN"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 晚上8:48
收件人: "FrankCAN/GAPNet"<GAPNet@noreply.github.com>;
抄送: "Confession"<1773507074@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [FrankCAN/GAPNet] ValueError: The passed save_path is not a validcheckpoint (#1)




Hi, that's sample. You can start from train.py that organizes the dataset, and training process. Besides, the classification model is called by "pred, end_points = MODEL.get_model(pointclouds_pl, is_training_pl, bn_decay=bn_decay)". For the classification model, it is coded in network.py file in the models folder. And the model function is get_model(), and the loss function is get_loss(). Finally, all other scripts are supporting files, for example, gat_layers.py is graph attention model.
