### ISSUE TITLE
spatial transform network

### ISSUE THREAD

**Issue by 16619884724** [FrankCAN/GAPNet#2]
Sorry to bother you again. Recently I have to quote your article in some work, so I am writing the relevant pytorch code.
In the picture,  spatial transform network of the paper illustration shows NxKx6. I understand that the 6D dimension feature is fed into the spatial transform network, but the [output_dim] defined by [gat_layers.py] in the code is 16-dimensional (16 channels), which means that in your paper the spatial transform network called [input_transform_net]  has two inputs, one is 19-dimensional feature called [neighbors_features], and the other is 16-dimensional feature called [locals_max_transform]. What does this have to do with the NxKx6 displayed in the transformation matrix in the image? Did I understand wrong?, I am eager to get your answer, thank you very much.

**Comment by FrankCAN** [comment]
Hi, spatial transform network is used to learn a 3 x 3 matrix for transformation invariant, which is illustrated in Figure 3 named "3 x 3 transform" in the paper. So no matter what dimension the input and output of [gat_layers.py] is, the output of the spatial transform network is always 3 x 3, which is then multiply with 3-dimension of spatial points to generate a spatial invariant 3-dimension points.

[neighbors_features] and [locals_max_transform] are high-level representations for points, they will be the input of the spatial transform network to generate 3 x 3 matrix, which will be more robust and also can improve accuracy.

I hope this can help you, please let me know if you are still confused. Thanks.

**Comment by 16619884724** [comment]
Thank you very much for your answer. I can understand the content you explained. Your work can also learn such a 3X3 transformation matrix.But I don't understand the meaning of NxKx6 in the spatial transform in Figure 3(I put this picture in the attachment.). 
In addition, I am writting code in  pytorch .When I define the spatial transform network, here is how DGCNN is defined: [self.trans_net = transform_net(6,3)], so I define the spatial transform network  as [self.trans_net = transform_net(19,16,3)] .  The 19-dimensional and 16-dimensional  features are fed to the network to learn a 3x3 transformation matrix , this numerical dimension transformation makes me a bit skeptical.As a beginner，this is not a common type of dimensional transformation. I am a bit skeptical and my English is not very good, I hope I can express my intentions. Thank you.


------------------ 原始邮件 ------------------
发件人: "FrankCAN"<notifications@github.com>;
发送时间: 2019年10月28日(星期一) 晚上7:45
收件人: "FrankCAN/GAPointNet"<GAPointNet@noreply.github.com>;
抄送: "Confession"<1773507074@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [FrankCAN/GAPointNet] spatial transform network (#2)




Hi, spatial transform network is used to learn a 3 x 3 matrix for transformation invariant, which is illustrated in Figure 3 named "3 x 3 transform" in the paper. So no matter what dimension the input and output of [gat_layers.py] is, the output of the spatial transform network is always 3 x 3, which is then multiply with 3-dimension of spatial points to generate a spatial invariant 3-dimension points.
 
[neighbors_features] and [locals_max_transform] are high-level representations for points, they will be the input of the spatial transform network to generate 3 x 3 matrix, which will be more robust and also can improve accuracy.
 
I hope this can help you, please let me know if you are still confused. Thanks.

**Comment by FrankCAN** [comment]
Hi, understood. I didn't notice this. I should have used GAPLayer module
rather than NxKx6. Thanks for your remind.

Best Regards
Frank

**Comment by 16619884724** [comment]
Thank you again for your excellent work.


Best wishes




------------------ 原始邮件 ------------------
发件人: "FrankCAN"<notifications@github.com>;
发送时间: 2019年10月28日(星期一) 晚上9:02
收件人: "FrankCAN/GAPointNet"<GAPointNet@noreply.github.com>;
抄送: "Confession"<1773507074@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [FrankCAN/GAPointNet] spatial transform network (#2)



Hi, understood. I didn't notice this. I should have used GAPLayer module
 rather than NxKx6. Thanks for your remind.
 
 Best Regards
 Frank
